Autodiscovery
trickstercache/trickster pull request #654
Opened 2023-03-12 12:28 UTC by jakenichols2719

Functionality for the automatic discovery and creation of backend sources through queries on Clients. Currently supported are etcd clusters and Kubernetes clusters, specifics on how to use can be found in the documentation for ALBs at `/docs/alb.md`.

2023-03-17 16:23 UTC, jakenichols2719 commented
Autodiscovery has been implemented for Kubernetes and ETCD queries.

This PR introduces a *lot* of lines of code--the k8s modules in particular have a significant number of dependencies, including multiple versions of the same dependencies. The main changes to `trickster` include:

- Introduction of package `autodiscovery` which defines the process for finding and instantiating backends
- Modification of package `alb` to use autodiscovery as configured

2023-03-28 19:09 UTC, jranson requested changes

2023-03-28 19:09 UTC, jranson commented on pkg/backends/templates/templates.go
> +var templateBackends map[string]*options.Options = make(map[string]*options.Options)
how does one reset the templateBackends back to an empty map (e.g., when reloading the application config when it has changed)?

2023-03-28 19:09 UTC, jranson commented on pkg/routing/routing.go
> +// Register a every backend marked as a template under package backend/templates.
grammar check here.  also, comment should start with the function name

2023-05-31 19:06 UTC, jakenichols2719 commented
So, my GPG certificate expired since I started working on this, and also, in retrospect I could have done a much better job on the configuration layout. I fixed those things in a new branch, so I'll be opening a new draft PR soon. Closing this one.

2023-05-31 19:06 UTC, closed without merging